---
- hosts: k3s_worker 
  user: chris
  become: yes
  become_user: root
  tasks:
  - name: Uninstall k3s from the agent node
    shell: /usr/local/bin/k3s-agent-uninstall.sh
- hosts: k3s_coordinator 
  user: chris
  become: yes
  become_user: root
  tasks:
  - name: Uninstall k3s from the coordinator node
    shell: /usr/local/bin/k3s-uninstall.sh